import React from 'react';
import { Link, useLocation } from 'react-router-dom';

/**
 * Capitalizes the first letter of a string, replaces hyphens with spaces,
 * and handles removing dynamic segments like IDs.
 * @param string The path segment.
 * @returns The formatted string or null if the segment should be skipped.
 */
const formatCrumb = (string: string): string | null => {
    // Simple check to skip IDs that might appear in the URL (e.g., /products/123)
    if (!isNaN(parseInt(string))) {
        return null; // Skip rendering IDs
    }

    const cleanString = string.split('?')[0];
    const spacedString = cleanString.replace(/-/g, ' ');

    // Format to Title Case (e.g., "my profile" -> "My Profile")
    return spacedString
        .split(' ')
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');
};

export const Breadcrumbs: React.FC = () => {
    const location = useLocation();
    // location.pathname example: "/user-guide/getting-started/installation"

    // Split the path and filter out empty strings (from the initial '/')
    const pathSegments: string[] = location.pathname
        .split('/')
        .filter((s) => s);

    // Build the breadcrumb structure, filtering out nulls generated by formatCrumb
    const breadcrumbs = pathSegments
        .map((crumb, index, array) => {
            // 1. Check for formatting (skip IDs)
            const formattedCrumb: string | null = formatCrumb(crumb);
            if (!formattedCrumb) return null; // Skip this crumb if it's an ID

            // 2. Reconstruct the URL up to the current segment
            // Note: We use the original pathSegments array for construction
            const originalSegments = pathSegments.slice(0, index + 1);
            const path: string = '/' + originalSegments.join('/');

            // 3. Determine if this is the last item
            const isLast: boolean = index === array.length - 1;

            return (
                <React.Fragment key={path}>
                    <li
                        className={`flex items-center text-sm ${isLast ? 'text-gray-900' : 'text-gray-500'}`}
                    >
                        {!isLast && (
                            <Link
                                to={path}
                                className="transition duration-150 ease-in-out hover:text-indigo-700"
                            >
                                {formattedCrumb}
                            </Link>
                        )}
                    </li>

                    {!isLast && (
                        <li className="mx-2 text-gray-400">
                            <svg
                                xmlns="http://www.w3.org/2000/svg"
                                fill="none"
                                viewBox="0 0 24 24"
                                stroke="currentColor"
                                className="size-3"
                            >
                                <path
                                    strokeLinecap="round"
                                    strokeLinejoin="round"
                                    d="m8.25 4.5 7.5 7.5-7.5 7.5"
                                />
                            </svg>
                        </li>
                    )}
                </React.Fragment>
            );
        })
        // Filter out any null values resulting from skipping dynamic IDs
        .filter((crumb): crumb is React.ReactElement => crumb !== null);

    return (
        <nav aria-label="Breadcrumb" className="py-4">
            <ol className="m-0 flex list-none items-center p-0">
                {/* Separator before other crumbs */}

                {/* Dynamic Breadcrumbs */}
                {breadcrumbs}
            </ol>
        </nav>
    );
};
